export const supportedRoutes = [
  '/box/22',
  '/box/21',
  '/box/13',
  '/me',
  '/me/cards',
  '/me/gacha_logs',
  '/history',
  '/lab',
  '/purchases',
  '/purchases/1',
  '/purchases/2',
  '/purchases/3',
  '/purchases/4',
  '/purchases/5',
  '/purchases/6',
  '/purchases/7',
  '/purchases/8',
  '/purchases/9',
  '/purchases/10',
  '/step-up',
  '/choice-gacha',
  '/choice-gacha/1',
  '/choice-gacha/2',
  '/step-up/2',
  '/me/tickets',
  '/me/coupons',
  '/me/addresses',
  '/me/addresses/new',
  '/me/addresses/demo',
  '/me/point_expire',
  '/me/megaboost',
  '/help/rank',
  '/email_update',
  '/password_update',
  '/password_reset',
  '/notifications',
  '/signup',
  '/login',
  '/phone-verification',
  '/login-bonus',
  '/help',
  '/terms',
  '/design-system',
  '/gacha/result',
];

// Public route names mirror the observed reference where the feature exists.
export const routeAliases: Record<string, string> = {
 '/mypage': '/me',
 '/mypage/profile': '/me',
 '/mypage/address': '/me/addresses',
 '/mypage/address/new': '/me/addresses/new',
 '/mypage/address/demo': '/me/addresses/demo',
 '/notification': '/notifications',
 '/coupon': '/me/coupons',
 '/point': '/purchases',
 '/others/help-oripa-rank': '/help/rank',
 '/oripa/Pokemon/22': '/box/22',
 '/oripa/Pokemon/21': '/box/21',
 '/oripa/Pokemon/13': '/box/13',
};
export const catalogRoutes = ['/oripa/All', '/oripa/Pokemon', '/oripa/OnePiece'];
export const allRoutes = [...supportedRoutes, ...Object.keys(routeAliases), ...catalogRoutes];
