/* September 8 catalogue and navigation revision; previous proposal snapshot is retained. */
const giftIcon='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 8h18v4H3zM5 12v9h14v-9M12 8v13"/><path d="M12 8H8a3 3 0 1 1 3-3l1 3Zm0 0h4a3 3 0 1 0-3-3l-1 3Z"/></svg>';
let giftReceived=false;
const superMenu=[['games','ゲームソフト'],['hardware','ゲーム機・周辺機器'],['cosmetics','コスメ・スキンケア'],['beauty','美容家電・ケア器具'],['food','グルメ・ドリンク'],['interior','生活雑貨・インテリア'],['hobby','トイ・ホビーグッズ'],['gadgets','家電・ガジェット'],['special','その他・特集']];
function desktopMenu(){const r=route(),link=(id,t)=>`<a href="#${id}" class="${r===id?'active':''}">${t}</a>`;return `<nav aria-label="PCサイドメニュー"><details open><summary>▤ オリパ</summary>${[['home','すべて'],['rush','<span class="rainbow-text">RUSH</span>'],['category-pokemon','ポケモン'],['category-onepiece','ワンピース'],['category-yugioh','遊戯王']].map(([id,t])=>link(id,t)).join('')}</details><details open><summary>▱ スーパー <small>NEW</small></summary>${superMenu.map(([id,t])=>link('super-'+id,t)).join('')}</details><details open><summary>▣ 獲得履歴</summary>${link('history','未選択')}${link('history?status=waiting','発送待ち')}${link('history?status=shipped','発送済み')}</details><details open><summary>アカウント</summary>${link('gifts','プレゼントボックス')}${link('mypage','マイページ')}${link('legacy-news','お知らせ')}${link('legacy-purchase','Pt購入履歴')}${link('legacy-address','お届け先登録・変更')}</details></nav>`;}
function catalogueThumb(p){return `<article class="catalogue-thumb"><a href="#product-${p.id}" aria-label="${esc(p.name)}の詳細を見る"><div class="catalogue-image"><img src="assets/${p.image}" alt="${esc(p.name)}" loading="lazy"></div><div class="catalogue-meta"><span><i class="coin">◉</i> <b>${fmt(p.price)}</b><small> / 1回</small></span><span class="catalogue-remaining">残り <b>${fmt(p.remaining)}</b> / ${fmt(p.total)}</span></div><div class="catalogue-stock"><span style="width:${Math.min(100,p.remaining/p.total*100)}%"></span></div></a></article>`;}
const catalogOldHome=home;
home=function(){return catalogOldHome().replace(/<div class="grid">[\s\S]*?<\/div><p class="screen-label">/,()=>{let items=D.products.filter(p=>(state.filter==='すべて'||p.tags.includes(state.filter))&&(state.category==='すべて'||p.category===state.category));if(state.sort==='cheap')items.sort((a,b)=>a.price-b.price);if(state.sort==='expensive')items.sort((a,b)=>b.price-a.price);return `<div class="grid catalogue-grid">${items.map(catalogueThumb).join('')}</div><p class="screen-label">`;});};
function giftsPage(){return `<div class="container narrow"><div class="breadcrumb"><a href="#home">オリパ一覧へ戻る</a></div>${heading('PRESENT BOX','プレゼントボックス')}<div class="gift-tabs"><b>未受取 ${giftReceived?0:1}</b><span>受取済み ${giftReceived?1:0}</span></div>${giftReceived?'<div class="surface empty"><h2>未受取のプレゼントはありません</h2><p>受取済み：ウェルカムプレゼント</p></div>':`<div class="surface gift-item"><div class="gift-mark">${giftIcon}</div><div><h2>ウェルカムプレゼント</h2><p>受取画面の確認用サンプル</p><small>報酬・期限は本番設定に接続します</small></div>${btn('受け取る','catalog-gift-receive')}</div>`}<p class="small">モック内の受取状態のみ変わります。実際のPt・商品は付与されません。</p></div>`;}
const catalogShell=shell,catalogRender=render,catalogAct=act;
shell=function(){catalogShell();const r=route(),standalone=['mypage','rank','play','effect','result','lab-player'].includes(r);document.documentElement.dataset.desktopMenu=standalone?'off':'on';$('#desktop-menu').innerHTML=standalone?'':desktopMenu();if(!standalone){$('#header').innerHTML=$('#header').innerHTML.replace('<a href="#mypage"',`<a href="#gifts" class="header-gift" aria-label="プレゼントボックス 未受取${giftReceived?0:1}件">${giftIcon}${giftReceived?'':'<span class="gift-badge">1</span>'}</a><a href="#mypage"`);$('#bottom-nav').innerHTML=$('#bottom-nav').innerHTML.replace('<a href="#mypage"',`<a href="#gifts" class="${r==='gifts'?'active':''}" ${r==='gifts'?'aria-current="page"':''}>${giftIcon}<span>プレゼント</span></a><a href="#mypage"`);}};
render=function(){catalogRender();const r=route();if(r==='gifts')$('#app').innerHTML=giftsPage();if(r.startsWith('super-')){const t=superMenu.find(([id])=>'super-'+id===r)?.[1]||'スーパー';$('#app').innerHTML=`<div class="container">${heading('SUPER',t)}<div class="surface"><p>このカテゴリは既存GRIMの商品一覧へ接続します。</p><p class="small">モックにはスーパーの商品データを含めていません。</p></div></div>`;}if(r==='history'&&(location.hash||location.search||'').includes('status=')){const t=(location.hash||location.search||'').includes('shipped')?'発送済み':'発送待ち';$('#app').innerHTML=`<div class="container">${heading('ACQUIRED ITEMS',t)}<div class="surface empty"><p>${t}の商品はありません（表示サンプル）。</p><a class="btn outline" href="#history">未選択の商品へ</a></div></div>`;}};
act=function(a){if(a==='catalog-gift-receive'){giftReceived=true;render();toast('プレゼントの受取表示を更新しました（モック）');return;}return catalogAct(a);};
render();
