/* Existing-style notifications; all entries are mock samples. */
const noticeBell='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 8-3 8h18s-3-1-3-8M10 21h4"/></svg>';
let noticeTab='personal',noticePage=1;
const notices=[{id:1,type:'personal',date:'2026年9月8日 09:00',title:'保有Ptの有効期限をご確認ください',body:'Ptの有効期限は保有状況の画面で確認できます。これは表示確認用の通知です。',read:false},{id:2,type:'news',date:'2026年9月8日 10:00',title:'RUSHのご案内',body:'RUSH一覧から無料のお試しを利用できます。',read:false},{id:3,type:'news',date:'2026年9月7日 12:00',title:'サービスからのお知らせ',body:'運営からのお知らせをこちらに表示します。内容はモック用サンプルです。',read:false}];
function noticeUnread(type){return notices.filter(x=>!x.read&&(!type||x.type===type)).length;}
function noticeBadge(n){return n?`<span class="notice-count">${n}</span>`:'';}
function noticeScreen(){const rows=notices.filter(x=>x.type===noticeTab),pages=Math.max(1,Math.ceil(rows.length/10));noticePage=Math.min(noticePage,pages);return `<div class="container notice-page"><div class="notice-page-heading"><a href="#home" aria-label="トップに戻る">‹ 戻る</a><h1>お知らせ</h1></div><div class="notice-content"><div class="notice-tabs" role="tablist" aria-label="通知の種類">${[['personal','あなたへの通知'],['charge','チャージ'],['news','お知らせ']].map(([id,t])=>`<button role="tab" aria-selected="${noticeTab===id}" class="${noticeTab===id?'active':''}" data-action="notice-tab:${id}">${t}${noticeBadge(noticeUnread(id))}</button>`).join('')}</div><div class="notice-toolbar"><button data-action="notice-read-all" ${noticeUnread()?'':'disabled'}>すべて既読にする</button></div><div role="tabpanel" aria-label="${{personal:'あなたへの通知',charge:'チャージ',news:'お知らせ'}[noticeTab]}">${rows.length?rows.slice((noticePage-1)*10,noticePage*10).map(x=>`<button class="notice-row" data-action="notice-open:${x.id}"><span class="notice-date">${!x.read?'<i aria-label="未読"></i>':''}${x.date}</span><span class="notice-title">${esc(x.title)}</span></button>`).join(''):'<div class="notice-empty">現在、チャージに関する通知はありません。</div>'}</div><div class="notice-pagination">${btn('前へ','notice-page:-1','outline',noticePage<=1?'disabled':'')}<span>${noticePage}</span>${btn('次へ','notice-page:1','outline',noticePage>=pages?'disabled':'')}</div><p class="small notice-sample">通知本文・件数は表示サンプルです。本番では既存のお知らせデータに接続します。</p></div></div>`;}
const noticeOldShell=shell,noticeOldRender=render,noticeOldAct=act;
shell=function(){noticeOldShell();if(route()==='legacy-news'){document.documentElement.dataset.desktopMenu='off';for(const id of ['#header','#category-nav','#footer','#bottom-nav','#desktop-menu'])$(id).innerHTML='';return;}const h=$('#header');if(h.innerHTML)h.innerHTML=h.innerHTML.replace('<a href="#gifts"',`<a href="#legacy-news" class="header-notice" aria-label="通知 未読${noticeUnread()}件">${noticeBell}${noticeBadge(noticeUnread())}</a><a href="#gifts"`);};
render=function(){noticeOldRender();if(route()==='legacy-news')$('#app').innerHTML=noticeScreen();};
act=function(a){const [k,v]=a.split(':');if(k==='notice-tab'){noticeTab=v;noticePage=1;render();}else if(k==='notice-read-all'){notices.forEach(x=>x.read=true);render();}else if(k==='notice-page'){noticePage+=Number(v);render();}else if(k==='notice-open'){const n=notices.find(x=>x.id===Number(v));if(!n)return;n.read=true;render();modal(`<span class="small">${n.date}</span><h2>${esc(n.title)}</h2><p style="margin:18px 0">${esc(n.body)}</p>${btn('閉じる','close','full')}`);}else return noticeOldAct(a);};
render();
