/* Proposal-only operations and existing-service screens. No production transactions. */
const ops={tags:[...new Set(D.products.flatMap(p=>p.tags))],selectedTags:[],couponUses:[],shippingView:'shipment',selected:[],shipments:[{id:'DEMO-DLV-001',status:'waiting',cards:[0,1],date:'2026/09/08 12:00'},{id:'DEMO-DLV-002',status:'shipped',cards:[2],date:'2026/09/07 10:00'}],gachaDrafts:[],gachaLogs:[],tagProduct:'entry',gachaType:'jp',thumb:''};
const opsTabsOld=adminTabs;
adminTabs=function(selected){return opsTabsOld(selected)+`<div class="admin-v2-tabs"><a href="#admin-tags">タグ管理</a><a href="#admin-gacha">ガチャ登録</a><a href="#admin-notices">注意文テンプレート</a><a href="#scope">追加実装・比較事項</a></div>`;};
function existingNotices(){return `<section class="existing-notices"><h2>注意事項</h2>${GRIM_EXISTING_NOTICES.map(x=>`<section><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p></section>`).join('')}</section>`;}
const opsLineupOld=tierLineup;tierLineup=function(p){return opsLineupOld(p)+existingNotices();};
const opsMypageOld=mypage;
mypage=function(){let h=opsMypageOld();h=h.replace(/<div class="surface settings-links">[\s\S]*?<\/div>/,`<div class="surface existing-account-links"><label>ユーザーID</label><div class="user-id"><code>GRIM-DEMO-0001</code>${btn('コピー','ops-copy-id','subtle')}</div>${[['history','カード獲得履歴'],['legacy-purchase','コイン購入履歴'],['legacy-gacha','ガチャ履歴'],['legacy-address','お届け先登録・変更'],['legacy-payment-cards','クレジットカード管理'],['rank','会員ランク詳細'],['legacy-email','メールアドレスの変更'],['legacy-password','パスワードの変更'],['legacy-contact','お問い合わせ'],['legacy-bonus','ボーナスオリパについて']].map(([r,t])=>`<a href="#${r}">${t}<span>›</span></a>`).join('')}</div>`);return h;};
function couponPage(){return `<div class="container narrow coupon-page"><h1>クーポンコードを入力</h1><p>発行されたクーポンコードを入力すると様々な特典を得ることができます。</p><label for="coupon-code">クーポンコード</label><input id="coupon-code" autocomplete="off" placeholder="コードを入力"><div id="coupon-error" role="alert"></div>${btn('登録する','ops-coupon','full')}<p class="small">動作確認用コード：GRIMDEMO（実際の特典付与はありません）</p><h2>利用履歴</h2>${ops.couponUses.length?ops.couponUses.map(x=>`<article class="coupon-use"><b>${esc(x.code)}</b><span>登録済み</span><p>${esc(x.date)} ／ 特典Pt 500（デモ）</p></article>`).join(''):'<div class="coupon-empty">利用履歴はありません</div>'}</div>`;}
function jpAvailable(g,n){return [1,10,100].includes(n)&&!['locked','expired','scheduled'].includes(state.jpMode)&&state.jp>=g.tickets*n&&state.coins>=g.points*n&&(g.stock??1000)>=n&&(g.limit??1000)-(g.used||0)>=n;}
jpGacha=function(){return `<div class="container"><h1>JP専用ガチャ</h1><p>毎月2日 10:00 〜 10日 23:59 ／ JPチケットとPtを消費します</p>${jpWallet()}<div class="grid">${renewal.jpGames.map((g,i)=>`<article class="product"><div class="jp-gacha-cover"><h2>${esc(g.name)}</h2><span>JACKPOT EXCLUSIVE</span></div><div class="product-body"><p>1回：JP ${fmt(g.tickets)}枚 ＋ ${fmt(g.points)} Pt</p><p class="small">残り ${fmt(g.stock??1000)}口 ／ JPゲージ加算対象外の表示例</p><div class="jp-multi-buttons">${[1,10,100].map(n=>`<div>${btn(n===1?'1回ガチャ':n+'連ガチャ',`ops-jp:${i}:${n}`,'',jpAvailable(g,n)?'':'disabled')}<small>JP ${fmt(g.tickets*n)}枚<br>＋ ${fmt(g.points*n)} Pt</small></div>`).join('')}</div><p class="small">保有券・Pt・残数・回数上限を満たす回数のみ利用できます。</p></div></article>`).join('')}</div><details class="surface"><summary>モックの所持数を変更して連続抽選を確認</summary>${btn('JP 1,000枚・1,000,000Ptにする','ops-jp-balance','outline')}</details></div>`;};
const sampleLogRows=[{date:'2026/09/08 14:29',name:'GRIM セレクション',times:100,spent:10000,top:[{image:'prize-1.png',name:'S賞 サンプル景品'}],coin:900},{date:'2026/09/08 14:20',name:'通常オリパ',times:10,spent:1000,top:[],coin:100}];
function gachaLogsPage(){return `<div class="container narrow"><h1>ガチャ履歴</h1><p class="small">A賞以上の獲得景品を表示します。コイン欄は消費量と獲得量を分けて表示しています（提案サンプル）。</p>${[...ops.gachaLogs,...sampleLogRows].map(x=>`<article class="gacha-log"><div class="log-head"><time>${x.date}</time><b>消費 ${fmt(x.spent)} Pt${x.jp?' ＋ JP '+fmt(x.jp)+'枚':''}</b></div><p>${esc(x.name)} ／ ${fmt(x.times)}回</p>${x.top.length?`<div class="log-prizes">${x.top.map(p=>`<figure><img src="assets/${p.image}" alt="${esc(p.name)}"><figcaption>${esc(p.name)}</figcaption></figure>`).join('')}</div>`:'<div class="log-empty">A賞以上の獲得景品はありません</div>'}<p class="small">獲得コイン：${fmt(x.coin)} Pt</p></article>`).join('')}</div>`;}
function itemTabs(status){return `<nav class="ops-item-tabs">${[['unselected','未選択'],['waiting','発送待ち'],['shipped','発送済み']].map(([id,t])=>`<a class="${status===id?'active':''}" href="/torecacorp/grim-renewal/items?status=${id}">${t}</a>`).join('')}</nav>`;}
function opsUnselectedItems(){return state.earned.length?state.earned.map(i=>D.prizes[i]):D.prizes;}
function deliveryPage(){const status=new URLSearchParams(location.search).get('status')||'unselected';return `<div class="container"><h1>カード獲得履歴</h1>${itemTabs(status)}${status==='unselected'?`<p class="small">未選択の商品はカード単位で選択します。モック内の獲得商品がない場合は比較用サンプルを表示します。</p><div class="ops-card-grid">${opsUnselectedItems().map((p,i)=>`<button class="ops-select-card ${ops.selected.includes(i)?'selected':''}" data-action="ops-select:${i}" aria-pressed="${ops.selected.includes(i)}"><img src="assets/${p.image}" alt="${esc(p.name)}"><span>${esc(p.name)}<br><b>${fmt(p.value)} コイン</b></span></button>`).join('')}</div><p>選択 ${ops.selected.length}枚 ／ 合計 ${fmt(ops.selected.reduce((s,i)=>s+(opsUnselectedItems()[i]?.value||0),0))} コイン</p>${btn('選択したカードの発送を確認','ops-shipping','',ops.selected.length?'':'disabled')}`:`<div class="delivery-comparison"><strong>発送管理の比較案（採用方式は未確定）</strong><div>${btn('配送ID単位（既存）','ops-delivery:shipment',ops.shippingView==='shipment'?'':'outline')}${btn('カード単位（変更案）','ops-delivery:card',ops.shippingView==='card'?'':'outline')}</div><p>${ops.shippingView==='shipment'?'1回の発送依頼を配送IDにまとめ、同じ配送先・進捗を共有します。':'カードごとに進捗を表示します。同梱・分割発送・追跡番号の管理方法も変更対象です。'}</p></div>${ops.shipments.filter(x=>x.status===status).map(x=>ops.shippingView==='shipment'?`<article class="shipment"><div class="log-head"><b>配送ID：${x.id}</b><span>${status==='waiting'?'発送待ち':'発送済み'}</span></div><p>受付日時 ${x.date}</p><h3>配送先</h3><p>デモユーザー ／ 登録住所（表示サンプル）</p><h3>カード ${x.cards.length}枚</h3><div class="shipment-images">${x.cards.map(i=>`<img src="assets/${D.prizes[i].image}" alt="${esc(D.prizes[i].name)}">`).join('')}</div></article>`:x.cards.map((i,j)=>`<article class="shipment card-shipment"><img src="assets/${D.prizes[i].image}" alt="${esc(D.prizes[i].name)}"><div><h3>${esc(D.prizes[i].name)}</h3><p>カードID：DEMO-${x.id}-${j+1}</p><p>${status==='waiting'?'発送待ち':'発送済み'} ／ 配送ID：${x.id}</p><p class="small">追跡番号：${status==='waiting'?'発送後に表示':'デモのため未設定'}</p></div></article>`).join('')).join('')||'<p>対象の配送はありません</p>'}`}</div>`;}
function tagAdmin(){const p=D.products.find(x=>x.id===ops.tagProduct)||D.products[0];return adminFrame('タグ管理・ガチャへの紐付け','admin-tags',`<div class="note warning">必須希望／日程次第で後続実装。タグ絞り込み・ソート・管理画面を追加実装として見積もります。</div><section class="surface"><h2>登録済みタグ</h2><div class="ops-tags">${ops.tags.map(t=>`<span class="tag">${esc(t)} <small>${D.products.filter(p=>p.tags.includes(t)).length}件</small></span>`).join('')}</div><label>新規タグ<input id="ops-tag-name" maxlength="30" placeholder="例：期間限定"></label>${btn('タグを登録','ops-tag-create','outline')}<div id="ops-error" role="alert"></div></section><section class="surface"><h2>ガチャに紐付ける</h2><select id="ops-tag-product">${D.products.map(x=>`<option value="${x.id}" ${x.id===p.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select><div class="ops-tags">${ops.tags.map(t=>btn(`${p.tags.includes(t)?'✓ ':''}${esc(t)}`,'ops-tag-toggle:'+encodeURIComponent(t),p.tags.includes(t)?'':'outline')).join('')}</div><p class="small">ガチャ登録画面でもタグの検索・既存タグ選択・新規登録を行えます。</p></section>`);}
function gachaAdmin(){return adminFrame('オリパ新規作成','admin-gacha',`<div class="note warning">通常オリパの既存登録を土台に、JP・RUSHチケット排出などの追加項目を設ける設計案です。他社固有のKP/KPPは採用しません。</div><section class="surface"><div class="fields"><label>ガチャ種別<select id="ops-gacha-type"><option value="jp" ${ops.gachaType==='jp'?'selected':''}>JP専用（JPチケット＋Pt）</option><option value="normal" ${ops.gachaType==='normal'?'selected':''}>通常（Pt）</option><option value="rush-ticket" ${ops.gachaType==='rush-ticket'?'selected':''}>RUSHチケット排出（Pt）</option></select></label>${field('ガチャ名','ops-gacha-name','') }<label>カテゴリ<select id="ops-gacha-category"><option>ポケモン</option><option>ワンピース</option><option>遊戯王</option></select></label><label>ヘッダー画像<input id="ops-gacha-image" type="file" accept="image/png,image/jpeg,image/webp"></label></div><label>タグを検索・新規入力<input id="ops-gacha-tag" list="ops-tag-options" placeholder="既存タグまたは新しいタグ"><datalist id="ops-tag-options">${ops.tags.map(t=>`<option value="${esc(t)}">`).join('')}</datalist></label>${btn('追加・紐付け','ops-draft-tag','outline')}<p id="ops-selected-tags">選択済み：${ops.selectedTags.map(esc).join(' ／ ')||'なし'}</p><div class="fields">${field('消費Pt（1口）','ops-gacha-pt',1000,'number','min="1"')}${ops.gachaType==='jp'?field('必要JPチケット（1口）','ops-gacha-jp',1,'number','min="1"'):''}${field('総口数','ops-gacha-stock',1000,'number','min="1"')}${field('1ユーザーの合計口数上限','ops-gacha-limit',100,'number','min="1"')}${field('販売開始','ops-gacha-start','2026-10-02T10:00','datetime-local')}${field('販売終了','ops-gacha-end','2026-10-10T23:59','datetime-local')}</div><label><input id="ops-gacha-eligible" type="checkbox" ${ops.gachaType==='jp'?'':'checked'}> JPゲージ加算対象</label><h3>景品登録</h3><p class="small">本番は既存カードDB・CSV登録を再利用し、景品タイプにRUSHチケットを追加します。下記はデモ用テーブルです。</p><div class="admin-scroll"><table class="settings-table"><thead><tr><th>景品タイプ</th><th>景品／チケットID</th><th>等級</th><th>口数</th></tr></thead><tbody><tr><td>${ops.gachaType==='rush-ticket'?'RUSHチケット':'カード'}</td><td>${ops.gachaType==='rush-ticket'?'crimson':'DEMO-CARD-001'}</td><td>A</td><td>1</td></tr><tr><td>交換専用Pt</td><td>DEMO-PT-001</td><td>B</td><td>残り口数</td></tr></tbody></table></div><h3>注意事項</h3><label>注意文テンプレート<select><option>既存GRIM共通注意事項</option></select></label><label>ガチャ個別の条件・注意文<textarea id="ops-gacha-note" rows="4" placeholder="回数制限、利用条件など"></textarea></label><h3>表示する抽選回数</h3><p>1回／10連／100連（資産・残数・口数上限を満たす場合に有効）</p><div id="ops-error" role="alert"></div>${btn('入力内容を確認・デモ登録','ops-gacha-save')}<p class="small">保存先はモックの実行中メモリです。本番公開・決済・在庫登録は行いません。</p></section><section class="surface"><h2>デモ登録したガチャ</h2>${ops.gachaDrafts.map(g=>`<p>${esc(g.name)} ／ ${g.kind} ／ ${g.stock}口</p>`).join('')||'<p>まだありません</p>'}</section>`);}
function scopePage(){return `<div class="container"><h1>実装範囲と比較事項</h1><div class="surface"><table class="settings-table"><thead><tr><th>項目</th><th>扱い</th><th>作業範囲</th></tr></thead><tbody>${[['注意事項・マイページメニュー','既存再利用','文面・項目の復元と全画面レイアウトへの配置'],['タグ・絞り込み・ソート','必須希望／後続実装の可能性','タグマスタ、ガチャ紐付け、API、候補表示、並び順'],['JPガチャ登録・連続抽選','追加実装','複数資産の同時消費、1/10/100連、残数・制限検証'],['クーポン入力・利用履歴','追加画面／既存API再利用を確認','コード検証、登録状態、使用済み・期限切れ・履歴'],['配送ID方式','既存維持案','配送単位でまとめる表示を継続'],['カード単位配送','比較案／別途工数','カード別進捗、同梱・分割、追跡番号、倉庫作業、既存データ移行'],['ガチャ履歴','既存維持＋表示変更案','A賞以上のみ画像表示、全結果の内部履歴は保持']].map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p>工数は既存コード・API・DBを確認後に算定します。画面モックの存在を実装済み機能として扱いません。</p><a class="btn" href="/torecacorp/grim-renewal/items?status=waiting">配送方式の比較画面</a></div>`;}
const opsOldRender=render;
render=function(){opsOldRender();const pages={'legacy-coupon':couponPage,'legacy-gacha':gachaLogsPage,history:deliveryPage,'admin-tags':tagAdmin,'admin-gacha':gachaAdmin,'admin-notices':()=>adminFrame('既存注意文テンプレート','admin-notices',existingNotices()),scope:scopePage};if(pages[route()])$('#app').innerHTML=pages[route()]();if(['legacy-payment-cards','legacy-bonus'].includes(route()))$('#app').innerHTML=`<div class="container narrow"><h1>${route()==='legacy-payment-cards'?'クレジットカード管理':'ボーナスオリパについて'}</h1><p>既存GRIMの機能・説明へ接続する画面です。今回のモックでは入力・変更を行いません。</p><a href="#mypage">マイページへ戻る</a></div>`;};
const opsOldAct=act;
act=function(a){const [k,v,n]=a.split(':');if(k==='ops-filter'){state.filter=decodeURIComponent(v);render();return;}if(k==='ops-coupon'){const code=$('#coupon-code').value.trim().toUpperCase();if(!code)return $('#coupon-error').textContent='クーポンコードを入力してください。';if(ops.couponUses.some(x=>x.code===code))return $('#coupon-error').textContent='このクーポンは登録済みです。';if(code!=='GRIMDEMO')return $('#coupon-error').textContent='コードが無効、または有効期限外です。';ops.couponUses.unshift({code,date:new Date().toLocaleString('ja-JP')});render();return;}
if(k==='ops-copy-id'){if(navigator.clipboard)navigator.clipboard.writeText('GRIM-DEMO-0001').then(()=>toast('コピーしました')).catch(()=>toast('GRIM-DEMO-0001 を選択してコピーしてください'));return;}
if(k==='ops-jp-balance'){state.jp=1000;state.coins=1000000;state.jpMode='active';render();return;}
if(k==='ops-jp'){const g=renewal.jpGames[Number(v)],times=Number(n);if(!g||!jpAvailable(g,times))return toast('必要な資産・残数・回数上限を満たしていません');let done=false;modal(`<h2>${esc(g.name)} ${times}回</h2><p>JP ${fmt(g.tickets*times)}枚 ＋ ${fmt(g.points*times)} Ptを消費します。</p><p>サンプル抽選です。実際の資産は消費しません。</p>${btn('確認して引く','confirm')}`,()=>{if(done||!jpAvailable(g,times))return;done=true;state.jp-=g.tickets*times;state.coins-=g.points*times;g.stock=(g.stock??1000)-times;g.used=(g.used||0)+times;if(renewal.eligible[g.id])renewal.monthlySpend+=g.points*times;state.earned.push(...Array(times).fill(0));ops.gachaLogs.unshift({date:new Date().toLocaleString('ja-JP'),name:g.name,times,spent:g.points*times,jp:g.tickets*times,top:[{image:'prize-1.png',name:'A賞 サンプル景品 × '+times}],coin:0});go('legacy-gacha');});return;}
if(k==='ops-delivery'){ops.shippingView=v;render();return;}if(k==='ops-select'){const i=Number(v);ops.selected=ops.selected.includes(i)?ops.selected.filter(x=>x!==i):[...ops.selected,i];render();return;}if(k==='ops-shipping'){modal(`<h2>発送依頼の確認（比較用）</h2><p>${ops.selected.length}枚を選択しています。</p><p>配送ID方式では1件の依頼にまとめます。カード方式では各カードの進捗を管理します。</p><p>採用方式・発送条件は未確定です。ここでは依頼を送信しません。</p>${btn('閉じる','close')}`);return;}
if(k==='ops-tag-create'||k==='ops-draft-tag'){const input=$(k==='ops-tag-create'?'#ops-tag-name':'#ops-gacha-tag');const t=input.value.trim().normalize('NFKC');if(!t||t.length>30)return toast('タグは1〜30文字で入力してください');if(!ops.tags.includes(t))ops.tags.push(t);if(k==='ops-draft-tag'&&!ops.selectedTags.includes(t))ops.selectedTags.push(t);if(k==='ops-draft-tag'){input.value='';$('#ops-selected-tags').textContent='選択済み：'+ops.selectedTags.join(' ／ ');toast('タグを追加しました');return;}render();return;}
if(k==='ops-tag-toggle'){const p=D.products.find(x=>x.id===ops.tagProduct),t=decodeURIComponent(v);p.tags=p.tags.includes(t)?p.tags.filter(x=>x!==t):[...p.tags,t];render();return;}
if(k==='ops-gacha-save'){const name=$('#ops-gacha-name').value.trim(),points=Number($('#ops-gacha-pt').value),tickets=ops.gachaType==='jp'?Number($('#ops-gacha-jp').value):0,stock=Number($('#ops-gacha-stock').value),limit=Number($('#ops-gacha-limit').value),start=$('#ops-gacha-start').value,end=$('#ops-gacha-end').value;if(!name||![points,stock,limit].every(x=>Number.isSafeInteger(x)&&x>0)||(ops.gachaType==='jp'&&(!Number.isSafeInteger(tickets)||tickets<=0))||!start||!end||start>=end)return $('#ops-error').textContent='名称・正の整数・販売開始より後の終了日時を確認してください。';const g={id:'demo-jp-'+(ops.gachaDrafts.length+1),name,points,tickets,stock,limit,kind:ops.gachaType,start,end,note:$('#ops-gacha-note').value,tags:[...ops.selectedTags],image:ops.thumb};ops.gachaDrafts.push(g);if(ops.gachaType==='jp'){renewal.jpGames.push(g);renewal.eligible[g.id]=$('#ops-gacha-eligible').checked;}modal(`<h2>デモ登録しました</h2><p>${esc(name)}</p><p>${ops.gachaType==='jp'?'JP専用ガチャ一覧に反映しています。':'入力内容をデモ登録一覧に保存しました。本番の商品一覧への公開は行いません。'}</p>${btn('登録一覧へ','ops-gacha-refresh')}`);return;}
if(k==='ops-gacha-refresh'){close();render();return;}return opsOldAct(a);};
document.addEventListener('change',e=>{if(e.target.id==='ops-tag-product'){ops.tagProduct=e.target.value;render();}if(e.target.id==='ops-gacha-type'){const ids=['ops-gacha-name','ops-gacha-pt','ops-gacha-stock','ops-gacha-limit','ops-gacha-start','ops-gacha-end','ops-gacha-note','ops-gacha-category'];const values=ids.map(id=>[id,$('#'+id).value]);ops.gachaType=e.target.value;render();values.forEach(([id,value])=>$('#'+id).value=value);}if(e.target.id==='ops-gacha-image'){const f=e.target.files[0];if(f&&f.size<=5*1024*1024)ops.thumb=URL.createObjectURL(f);else toast('画像は5MB以下で選択してください');}});
const opsHomeOld=home;
home=function(){return opsHomeOld().replace(/<div class="filters">[\s\S]*?<select id="sort"/,`<div class="filters">${['すべて',...ops.tags].map(t=>`<button class="chip ${state.filter===t?'active':''}" data-action="ops-filter:${encodeURIComponent(t)}">${esc(t)}</button>`).join('')}<select id="sort"`);};
