/* Review additions: explicit prototype boundaries, rank art and resumable demo. */
const auditState={rank:'BRONZE',art:{},decisions:{},period:'next-month'};
try{auditState.art=JSON.parse(localStorage.getItem('grim-rank-art')||'{}');const saved=JSON.parse(localStorage.getItem('grim-rush-resume')||'null');if(saved?.run?.config&&Array.isArray(saved.run.results)&&!rlValidate(saved.run.config)){rlRun=saved.run;if(saved.rushId)renewal.rushEditing=saved.rushId;if(saved.tickets)state.tickets=saved.tickets;}}catch{}
function auditPersistRun(){try{localStorage.setItem('grim-rush-resume',JSON.stringify({run:rlRun,rushId:renewal.rushEditing,tickets:state.tickets}));}catch{toast('この端末に進行を保存できません。再読込後の復帰は利用できません。');}}
function auditConfig(id){return rlPublished[id]?.config||{...rlDefault(),name:D.rushes.find(x=>x.id===id)?.name||id};}
function auditRateLabel(id){const c=auditConfig(id),rates=c.rules.filter(x=>x.from<c.max).map(x=>x.rate);return rates.length?Math.min(...rates)===Math.max(...rates)?String(rates[0]):`${Math.min(...rates)}〜${Math.max(...rates)}`:'—';}
function auditOdds(id){const c=auditConfig(id);return `<div class="audit-odds"><b>お試しの適用ルール</b><p>最大${c.max}ステージ（初回を含む）。初回報酬あり。各段階の報酬を決めた後、次へ進むか判定します。</p>${c.rules.map(x=>`<p>${x.from}〜${Math.min(x.to,c.max)}段階：${x.from>=c.max?'上限で終了':`次段階へ進む確率 ${x.rate}%${x.to>=c.max?'（最終段階を除く）':''}`}</p>`).join('')}<p>段階による継続率です。完走率・還元率・特定景品の当選率ではありません。開始時に全結果を生成し、演出やまとめて表示で再抽選しません。</p><small>本番未接続のデモ。商品・確率・原価の法務／収支確認は未完了です。</small></div>`;}
const auditCoverOld=cover;cover=function(r,d){const copy={...r,rate:auditRateLabel(r.id)};return auditCoverOld(copy,d).replace('継続率</div>','次へ進む確率（段階別）</div>');};
const auditRushDetailOld=rushDetail;
rushDetail=function(){let html=auditRushDetailOld();if(state.rushTab==='ranking')html=html.replace(/<div class="ranking">[\s\S]*?<p class="small">上位10件を表示・デモ結果は対象外<\/p><\/div>/,'<div class="ranking"><h2>継続回数ランキング</h2><p>本番データ接続後に上位10件を表示します。</p><p class="small">旧サンプルの回数は現在の最大ステージ数と一致しないため非表示にしています。</p></div>');return html.replace('排出商品はチケットを獲得した時点で確定します。','このデモではRUSH開始時に全結果が確定します。本番の確定時点は合意対象です。').replace('<div class="surface" id="rush-section">',auditOdds(state.rushId)+'<div class="surface" id="rush-section">');};
const auditRushCardOld=rushCard;rushCard=function(r){return auditRushCardOld({...r,rate:auditRateLabel(r.id)}).replace('</article>',`<div class="audit-card-rule">最大${auditConfig(r.id).max}ステージ・初回報酬あり<br>継続率は段階別。詳細で確認できます。</div></article>`);};
const auditPlayerOld=rlPlayer;rlPlayer=function(){return auditPlayerOld().replace('<div class="rl-player-top">','<div class="rl-player-top">').replace('<div class="surface"><h2>',`<div class="audit-resume"><a href="/torecacorp/grim-renewal/rush">中断してRUSH一覧へ</a><p>この端末の同じブラウザー内で再開できます。本番のアカウント単位復帰・資産保証は未接続です。</p></div><div class="surface"><h2>`);};
const auditListOld=rushList;rushList=function(){return (rlRun&&!rlRun.done?`<div class="container"><div class="surface"><b>進行中のRUSHがあります</b><p>${esc(rlRun.config.name)} ／ 公開済み ${Math.max(0,rlRun.index+1)}段階</p>${btn('続きから再開','audit-resume')}</div></div>`:'')+auditListOld();};
const auditCompactOld=compactMemberRank;
compactMemberRank=function(){const r=rankFor(renewal.lifetime),art=auditState.art[r.name]||{};let h=auditCompactOld();if(art.icon)h=h.replace(crownSvg,`<img class="audit-rank-icon" src="${art.icon}" alt="">`);if(art.background)h=h.replace('<div class="member-crown">',`<img class="audit-rank-bg" src="${art.background}" alt=""><div class="member-crown">`);return h.replace(/★×\d+/,r.stars<=5?'★'.repeat(r.stars):'★×'+r.stars);};
function auditRankAdmin(){const art=auditState.art[auditState.rank]||{};return adminFrame('ランク別アイコン・背景','admin-rank-art',`<div class="surface"><label>対象ランク<select id="audit-rank">${SYS.ranks.map(r=>`<option ${r.name===auditState.rank?'selected':''}>${r.name}</option>`).join('')}</select></label><p>ランクごとにアイコンと背景を差し替えます。Lv条件・還元率は画像に焼き込まず文字で表示します。</p><div class="fields"><label>アイコン：512×512推奨<input type="file" accept="image/png,image/jpeg,image/webp" data-audit-art="icon"></label><label>背景：1600×400推奨<input type="file" accept="image/png,image/jpeg,image/webp" data-audit-art="background"></label></div><p class="small">PNG/JPEG/WebP、各2MB以下。アイコンはcontain、背景はcover。文字の安全領域を確保してください。</p><div class="audit-art-preview" style="${art.background?`background-image:url(${art.background})`:''}">${art.icon?`<img src="${art.icon}" alt="">`:crownSvg}<b>${auditState.rank}</b></div>${btn('このランクの画像を解除','audit-art-clear','outline')}<p>保存はこのブラウザー内です。管理権限・CDN・本番アップロードは追加実装対象です。</p></div>`);}
const auditSections=[
 ['① 累計ランク','Lv.1〜999と全11ランクの金額境界は実装済み。Lv.50はBRONZE、Lv.100がSILVER。課金デモの確定直後に再計算。LEGENDは5,000万円、★は以後500万円ごと。★5は7,500万円。元の仕様に★上限はない。','本番の決済確定イベント・重複防止・返金時扱いを実装する。ランク別画像設定は今回モック追加。'],
 ['② SEASON PASS','到達地点の追加削除、Pt・RUSHチケット・クーポン・限定商品という種別表示はある。現行1地点1報酬で、ランク別条件と複数報酬の付与台帳は未実装。','1地点にコイン／チケット種別ID／カード・BOX商品IDを複数紐付ける。月初ランクで当月の報酬プランを固定する案。'],
 ['③ JP','課金額とは別の対象消費Ptを集計。対象外商品フラグとランク別の閾値・枚数設定がある。現在の管理UIは10ゲージ×5地点。','任意ゲージ数・地点数を扱う管理UI、設定版の期間固定、月次確定と付与台帳は追加実装。枚数の差別化を初期案にし、ゲージ数の差も設定モデルで許容する。'],
 ['②③ 設定反映','現在の旧管理モックは編集値が即座にプレビューへ反映される。本番の次月予約ではない。','経済条件は翌月1日適用を原則。公開済み当月版を直接書換えない。当月変更は別承認の差分補填イベント。テーマのみ別バージョンで即時適用可能にする案。'],
 ['④ RUSH','開始時に報酬テーブルの重み抽選と継続抽選を最後まで実行し、結果配列を保持。まとめて表示は同じ配列の全公開。旧チケットプレイの固定8結果は新デモへ統一。','本番はサーバー確定結果・設定版・進捗・台帳を保存。ユーザー単位で進行中1件。券発行時にルール版固定、初回開始時に全結果を確定する案。'],
 ['RUSH中断・障害','同一ブラウザー内の保存・再開を今回追加。途中で別RUSHを開始せず既存プレイの再開へ誘導。','本番はアカウント単位で復帰。通信断はrun IDで照会、再抽選・再消費なし。動画失敗時は静止結果。端末保存のみで本番保証はしない。'],
 ['チケット入手・報酬','同じ種類・同じルール版なら購入／排出／配布による優遇差を設けない案。入手経路だけ台帳に残す。','ドロップは登録画面の景品種別見本まで。実抽選→券発行の処理は未実装。RUSH報酬の現物ID・在庫予約・発送連携も未実装。']
];
function auditReviewPage(){return `<div class="container"><h1>主軸①〜④ 仕様確認・合意事項</h1><p>本番完成の確認ではなく、モック実装と追加仕様の差分です。合意前の推奨案を含みます。</p>${auditSections.map(([title,now,next])=>`<section class="surface"><h2>${title}</h2><h3>現状</h3><p>${now}</p><h3>追加仕様・合意案</h3><p>${next}</p></section>`).join('')}<section class="surface"><h2>テーマ素材の推奨規格</h2><p>ランクアイコン512×512、ランク背景1600×400、パス背景1600×800、ゲージ背景/進行1600×80、先端256×256（透過）、周辺装飾800×800（透過）、報酬アイコン256×256、ボタン600×160（9-slice想定）。静止画PNG/WebP/JPEG、各2MB以下。本番の配信規格は実装時に確定。</p><p>旧テーマ管理は配色・素材プレビュー。ボタン画像とランク別のシーズン報酬プランは本番追加仕様です。</p><a href="/torecacorp/grim-renewal/admin/theme">テーマ管理</a> ／ <a href="/torecacorp/grim-renewal/admin/rank-art">ランク画像管理</a></section><section class="surface"><h2>クライアント確認項目</h2><ol><li>元のランク表を維持し、★は上限なしでよいか。</li><li>シーズンパスのランクは月初固定でよいか。月中昇格は翌月から適用。</li><li>②③の経済条件は次月適用を原則としてよいか。</li><li>RUSHは券発行時に版を固定、開始時に全結果確定としてよいか。</li><li>進行中RUSHは全種類を通して1件、任意中断で既得報酬を失わないでよいか。</li><li>同種類・同版のチケットは入手経路で有利不利を変えないでよいか。</li><li>未開始券の期限と開始済みプレイの復帰期限・障害補償をどうするか。</li><li>確率・還元表示と特典の扱いを法務確認後に公開する。</li></ol></section><section class="surface"><h2>法務確認用資料</h2><p>抽選の確定時点、継続率と完走率の違い、上限、獲得価値、券の対価性と失効、景品類・賭博・資金決済・通信販売の該当性を確認します。合法性の判断は未了です。</p></section></div>`;}
const auditAdminTabsOld=adminTabs;adminTabs=function(s){return auditAdminTabsOld(s)+`<div class="admin-v2-tabs"><a href="/torecacorp/grim-renewal/review/pillars">①〜④仕様確認</a><a href="/torecacorp/grim-renewal/admin/rank-art">ランク画像管理</a></div>`;};
const auditOldRender=render;render=function(){auditOldRender();if(route()==='pillar-review')$('#app').innerHTML=auditReviewPage();if(route()==='admin-rank-art')$('#app').innerHTML=auditRankAdmin();};
const auditOldAct=act;
act=function(a){const [k,v]=a.split(':');if(k==='audit-resume'){go('lab-player');return;}if(k==='audit-art-clear'){delete auditState.art[auditState.rank];localStorage.setItem('grim-rank-art',JSON.stringify(auditState.art));render();return;}
if(['demo','start','rl-run'].includes(k)){if(rlRun&&!rlRun.done){modal('<h2>進行中のRUSHがあります</h2><p>新しいRUSHを開始する前に、進行中の結果をご確認ください。</p>'+btn('続きから再開','audit-resume'));return;}if(k==='rl-run'){auditOldAct(a);auditPersistRun();return;}const id=v,c=auditConfig(id);const beginRun=()=>{if(k==='start'&&!(state.tickets[id]>0))return toast('チケットが不足しています');if(k==='start')state.tickets[id]--;renewal.rushEditing=id;rlRun=rlMakeRun(c);rlRun.rushId=id;rlRun.source=k==='start'?'ticket-demo':'free-demo';auditPersistRun();go('lab-player');};if(k==='start')modal('<h2>チケットでRUSHを開始</h2><p>モックのチケット1枚を消費します。開始時に全結果が確定します。実景品は付与しません。</p>'+btn('開始する','confirm'),beginRun);else beginRun();return;}
auditOldAct(a);if(['rl-next','rl-bulk','rl-publish'].includes(k))auditPersistRun();};
document.addEventListener('change',e=>{if(e.target.id==='audit-rank'){auditState.rank=e.target.value;render();}const type=e.target.dataset?.auditArt;if(type){const file=e.target.files?.[0],rank=auditState.rank;if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>2*1024*1024)return toast('PNG/JPEG/WebP、2MB以下の画像を選択してください');const reader=new FileReader();reader.onload=()=>{auditState.art[rank]??={};auditState.art[rank][type]=reader.result;try{localStorage.setItem('grim-rank-art',JSON.stringify(auditState.art));render();}catch{toast('画像を保存できません。サイズを小さくしてください');}};reader.readAsDataURL(file);}});
