/* v2の画面と管理モック。確定取引の計算・資産台帳は本番サーバーで実装する。 */
const renewal = {
  lifetime: 725000, monthlyCharge: 37500, monthlySpend: 312000,
  jpRank: 'SILVER', month: '2026-09', claimed: [],
  theme: 'classic', globalTheme: false, themeOverrides: {}, assets: {},
  milestones: structuredClone(SYS.milestones), seasonTitle: 'AUTUMN CHALLENGE',
  seasonStart: '2026-09-01', seasonEnd: '2026-09-30',
  jpStart: '2026-09-01', jpEnd: '2026-09-30',
  eligible: Object.fromEntries(D.products.map(p=>[p.id, !p.gate])),
  jpGames: [{id:'jp1',name:'JP ENTRY',tickets:1,points:1000}, {id:'jp10',name:'JP PREMIUM',tickets:10,points:5000}, {id:'jp50',name:'JP SPECIAL',tickets:50,points:20000}],
  rushEditing: 'crimson', rushSettings: {}, rewardHistory: []
};
try { const saved=JSON.parse(localStorage.getItem('grim-renewal-v2')); if(saved)for(const key of ['theme','globalTheme','themeOverrides','assets','milestones','seasonTitle','seasonStart','seasonEnd','jpStart','jpEnd','eligible','jpGames','rushSettings'])if(saved[key]!==undefined)renewal[key]=saved[key]; } catch {}
D.ranks=SYS.ranks.map(r=>r.name);
state.adminRank='BRONZE'; state.rank='SILVER'; state.adminConfigs={};
try { const saved=JSON.parse(localStorage.getItem('grim-jp-config-v2')); if(saved?.rankConfigs)state.adminConfigs=saved.rankConfigs; } catch {}
const crownSvg='<svg viewBox="0 0 60 50" aria-hidden="true"><path fill="currentColor" d="M5 12 18 25 30 4 42 25 55 12 49 40H11Z"/><path fill="none" stroke="currentColor" stroke-width="4" d="M13 47h34"/></svg>';
const themeValues=()=>({...SYS.themes[renewal.theme],...renewal.themeOverrides});
function saveRenewal(){ try{localStorage.setItem('grim-renewal-v2',JSON.stringify(renewal));toast('設定をこのブラウザーに保存しました');}catch{toast('保存容量を超えています。画像を小さくしてください。')} }
function themeStyle(){const t=themeValues();return `--season-panel:${t.panel};--season-accent:${t.accent};--season-fill:${t.fill};--season-track:${t.track};${renewal.assets.background?`background-image:linear-gradient(#0005,#0005),url(${renewal.assets.background});background-size:cover;`:''}`;}
function rankCard(){
  const r=rankFor(renewal.lifetime), range=r.max?r.max-r.min:5000000;
  const percent=r.max?Math.min(100,100*(r.total-r.min)/range):100;
  const stars=r.stars>5?'★ × '+fmt(r.stars):'★'.repeat(r.stars);
  return `<section class="rank-status ${r.name==='LEGEND'?'legend':''}" style="--rank-color:${r.color}">${renewal.assets.rankDecor?`<img class="theme-rank-decoration" src="${renewal.assets.rankDecor}" alt="">`:''}<span class="eyebrow">LIFETIME STATUS · 永久ステータス</span><div class="rank-heading"><div class="crown">${crownSvg}</div><div><div class="rank-name">${r.name}</div><div class="rank-level"><small>Lv.</small> ${r.level} <span class="rank-stars">${stars}</span></div></div></div><div class="rank-metrics"><span>累計課金額 <b>¥${fmt(r.total)}</b></span><span>${r.name==='LEGEND'?'次の★':'次のLv.'}まで ¥${fmt(r.next-r.total)}</span></div><div class="progress"><span style="width:${percent}%"></span></div><div class="rank-metrics"><span>${r.name==='LEGEND'?'Lv.999 MAX · 500万円ごとに★追加':'ランク・レベルは原則下がりません'}</span><a href="#rank">ランクと特典 →</a></div></section>`;
}
function rankPage(){const r=rankFor(renewal.lifetime);return `<div class="container rank-detail-page"><div class="rank-detail-heading"><a href="#mypage" aria-label="マイページに戻る">‹</a><h1>会員ランク</h1></div><div class="rank-detail-status">${compactMemberRank()}</div><section class="rank-explanation"><h2>ランクについて</h2><p>GRIMでの累計課金額に応じて成長する会員ステータスです。到達したランクとレベルは原則として下がらず、翌月以降も維持されます。</p><h2>ランク特典</h2><p>ポイント購入時の還元率など、ランクに応じた恒久特典を設定予定です。具体的な還元率・その他特典は決定後にご案内します。</p><div class="rank-benefit-table"><table><thead><tr><th>ランク</th><th>Pt還元率</th></tr></thead><tbody>${SYS.ranks.map(x=>`<tr ${x.name===r.name?'class="current"':''}><td><div class="rank-table-name"><i style="background:${x.color}"></i><strong>${x.name}</strong>${x.name===r.name?'<span>現在</span>':''}</div></td><td>未定</td></tr>`).join('')}</tbody></table></div><h2>ご案内</h2><p>還元率と特典内容は設定準備中です。月間の課金進捗と報酬はSEASON PASSから確認できます。</p></section></div>`;}

function seasonCard(compact=false){
 const t=themeValues(),p=seasonProgress(renewal.monthlyCharge,renewal.milestones);
 return `<section class="season-card ${compact?'compact':''} ${renewal.theme}" style="${themeStyle()}"><div class="season-decor">${renewal.assets.decor?`<img src="${renewal.assets.decor}" width="100" alt="">`:t.decor}</div><div class="season-top"><div><span class="eyebrow">GRIM SEASON PASS</span><h2>${esc(renewal.seasonTitle)}</h2><span class="season-month">${esc(renewal.seasonStart)} 〜 ${esc(renewal.seasonEnd)}</span></div>${compact?'<a class="btn outline small-btn" href="#season">詳細 →</a>':''}</div><div class="season-summary"><div><small>今月の課金額</small><br><strong>¥${fmt(renewal.monthlyCharge)}</strong></div><div><small>報酬地点の到達数</small><br><strong>${p.achieved}<small> / ${renewal.milestones.length}</small></strong></div></div><div class="season-track" ${renewal.assets.track?`style="background-image:url(${renewal.assets.track});background-size:cover"`:''}><div class="season-fill" style="width:${p.percent}%;${renewal.assets.fill?`background-image:url(${renewal.assets.fill});background-size:cover;`:''}"><span class="season-tip">${renewal.assets.tip?`<img src="${renewal.assets.tip}" alt="">`:t.tip}</span></div></div><div class="season-next"><div><small>${p.next?'次の報酬：'+esc(p.next.name):'すべての報酬地点に到達しました'}</small><br><strong>${p.next?'あと ¥'+fmt(p.remaining):'FINAL COMPLETE'}</strong></div><span class="small">翌月1日に新しいシーズンへ</span></div><div class="season-rewards">${renewal.milestones.map((m,i)=>{const reached=renewal.monthlyCharge>=m.amount,claimed=renewal.claimed.includes(i);return `<article class="season-reward ${reached?'achieved':''} ${m===p.next?'next':''}"><div class="reward-icon">${m.image?`<img src="${m.image}" alt="">`:esc(m.icon)}</div><h3>${esc(m.name)}</h3><p>${esc(m.kind)} × ${fmt(m.qty)}</p><div class="amount">¥${fmt(m.amount)}</div>${btn(claimed?'受取済み':reached?'受け取る':'未到達','v2-claim:'+i,claimed?'subtle':'white',claimed||!reached?'disabled':'')}</article>`}).join('')}</div></section>`;
}
function seasonPage(){return `<div class="container season-detail-page">${heading('MONTHLY REWARDS','GRIM SEASON PASS',`<a class="btn outline" href="#admin-season">運営設定を確認</a>`)}<div class="note info">金額ラインと報酬は画面確認用サンプルです。追加のパス購入は想定していません。</div>${seasonCard()}<div class="surface"><h2>今月の積み重ねが、報酬に。</h2><p>当月の課金額でゲージが進みます。累計ランクやポイント消費とは別に集計します。</p><div class="product-actions season-demo-actions">${btn('課金デモ +12,500円','v2-charge','outline')}${btn('全地点達成の表示','v2-season-full','outline')}</div><p class="small">到達した報酬はプレゼントBOXに届きます。受け取りはプレゼントBOXで行えます。</p>${renewal.rewardHistory.length?`<h3>受取履歴</h3>${renewal.rewardHistory.map(x=>`<p>${esc(x)}</p>`).join('')}`:''}</div><p class="screen-label">S01 / 現在月・次報酬・差額・全報酬を表示</p></div>`;}
const oldMypage=mypage,oldHome=home,oldRender=render,oldShell=shell,oldAct=act,oldAdmin=admin,oldPlay=play;
const systemsNav=()=>`<div class="system-links"><a href="#rank">♛ 累計ランク / Lv.</a><a href="#season">✦ SEASON PASS</a><a href="#jackpot">JP ジャックポット</a><a href="#rush">ϟ RUSH</a></div>`;
home=function(){return oldHome();};
function compactMemberRank(){const r=rankFor(renewal.lifetime);return `<a class="member-rank-summary ${r.name==='LEGEND'?'legend':''}" href="#rank" style="--rank-color:${r.color}"><div class="member-crown">${crownSvg}</div><div class="member-rank-copy"><small>累計会員ランク</small><strong>${r.name} <span>Lv.${r.level}${r.stars?' ★×'+r.stars:''}</span></strong><p>ポイント還元率：設定準備中</p></div><span aria-hidden="true">›</span></a>`;}
function compactMemberSeason(){const p=seasonProgress(renewal.monthlyCharge,renewal.milestones);return `<a class="member-season-summary" href="#season" style="${themeStyle()}"><div class="member-season-title"><strong>GRIM SEASON PASS</strong><span aria-hidden="true">›</span></div><div class="member-season-period">${esc(renewal.seasonStart)} 〜 ${esc(renewal.seasonEnd)}</div><div class="member-season-charge"><span>今月の課金額</span><strong>¥${fmt(renewal.monthlyCharge)}</strong></div><div class="member-season-bottom"><span>報酬地点 <b>${p.achieved} / ${renewal.milestones.length}</b></span><span>${p.next?'次の報酬まであと <b>¥'+fmt(p.remaining)+'</b>':'全報酬地点に到達'}</span></div></a>`;}
mypage=function(){let html=oldMypage();html=html.replace(/<a class="rank-card"[\s\S]*?<\/a>/,compactMemberRank()+compactMemberSeason());html=html.replace(/<aside class="account-nav">[\s\S]*?<\/aside>/,'');html=html.replace(heading('MY ACCOUNT','マイページ'),'<div class="member-page-heading"><a class="member-back" href="#home" aria-label="オリパ一覧に戻る">‹ 戻る</a><h1>マイページ</h1></div>');return html.replace('class="container"','class="container member-page"');};
shell=function(){oldShell();document.documentElement.dataset.grimPage=route();if(['mypage','rank'].includes(route())){for(const id of ['#header','#category-nav','#footer','#bottom-nav'])$(id).innerHTML='';}};

function jpRankConfig(){return state.adminConfigs[renewal.jpRank]||D.gaugeDefaults();}
gauge=function(index,progress,locked=false){const settings=jpRankConfig(),g=settings[index],start=index?settings[index-1].at(-1).threshold:0,end=g.at(-1).threshold;return `<div class="gauge"><span class="gauge-label">ゲージ${index+1}</span><div class="gauge-track"><div class="milestones" style="position:relative;height:46px">${g.map(m=>{const pos=(m.threshold-start)/(end-start)*100;return `<span class="milestone ${!locked&&progress>=pos?'done':''}" style="position:absolute;left:${pos}%;transform:translateX(-100%)">${m.reward}<br><i class="jp-token">JP</i></span>`}).join('')}</div><div class="progress"><span style="width:${locked?0:progress}%"></span></div></div></div>`;};
jpCard=function(){const locked=state.jpMode==='locked',full=state.jpMode==='full',settings=jpRankConfig(),amount=full?settings.at(-1).at(-1).threshold:renewal.monthlySpend,p=jpProgress(locked?0:amount,settings);const active=settings.findIndex(g=>amount<g.at(-1).threshold),count=locked?1:active<0?settings.length:active+1;return `<div class="jp-card ${locked?'progress-locked':''}"><a class="jp-heading" href="#jackpot"><div><h2>ジャックポット</h2><p>対象オリパの消費Ptが、翌月のJPに。</p></div><span>›</span></a><div class="jp-body"><div class="jp-context"><span>${esc(renewal.jpStart)} 〜 ${esc(renewal.jpEnd)}</span><span>適用ランク：${locked?'BEGINNER':renewal.jpRank}</span></div><p>当月対象消費 <b>${fmt(locked?0:amount)} Pt</b></p>${Array.from({length:count},(_,i)=>{const start=i?settings[i-1].at(-1).threshold:0,end=settings[i].at(-1).threshold;return gauge(i,Math.max(0,Math.min(100,(amount-start)/(end-start)*100)),locked)}).join('')}${locked?'<p>JP対象ランクから利用できます</p>':`<p class="small">${p.next?'次の獲得地点まで あと '+fmt(p.next.threshold-amount)+' Pt':'全ゲージ達成'}</p><div class="jp-summary"><span>当月獲得確定・翌月利用予定<br><small>翌月1日付与・開催は2日10:00から</small></span><span><i class="jp-token">JP</i> <strong>${p.earned}</strong> 枚</span></div>`}</div></div>`;};
jpGacha=function(){const unavailable=['locked','expired','scheduled'].includes(state.jpMode);return `<div class="container">${heading('NEXT MONTH REWARDS','JP専用ガチャ',`<a class="btn outline" href="#jackpot">JP詳細</a>`)}<div class="home-notice">毎月2日 10:00 〜 10日 23:59 / チケットとPtの両方が必要です</div>${jpWallet()}<div class="grid">${renewal.jpGames.map((g,i)=>`<article class="product"><div class="jp-gacha-cover"><span class="tag gold">JP ${g.tickets}枚</span><h2>GRIM<br>${esc(g.name)}</h2><p>JACKPOT EXCLUSIVE</p></div><div class="product-body"><div class="dual-price"><b><i class="jp-token">JP</i> ${fmt(g.tickets)}枚</b> ＋ <b>${fmt(g.points)} Pt</b></div><p class="small">価格・商品はサンプル / JP加算対象外の例</p>${btn(unavailable?'期間外または利用対象外':'このガチャを引く','v2-jp-draw:'+i,'full',unavailable?'disabled':'')}</div></article>`).join('')}</div><p class="screen-label">J02 / 必要券枚数と必要Ptが異なる複数商品</p></div>`;};
function adminTabs(selected){return `<div class="admin-v2-tabs">${[['admin','JPランク設定'],['admin-season','シーズン報酬'],['admin-theme','着せ替え'],['admin-jp','JP対象と商品'],['admin-rush','RUSH管理']].map(([id,name])=>`<a class="${selected===id?'active':''}" href="#${id}">${name}</a>`).join('')}</div>`;}
admin=function(){return oldAdmin().replace('<div class="admin-layout">',adminTabs('admin')+'<div class="admin-layout">').replace('10ゲージ × 5スロット','10ゲージ × 5スロット（初期構成）');};
function adminFrame(title,route,body){return `<div class="container">${heading('GRIM MANAGEMENT',title)}${adminTabs(route)}<div class="note info">運営向け画面モック。保存はこのブラウザーのみ。本番の予約公開・承認・資産付与は接続されません。</div>${body}</div>`;}
const field=(label,id,value,type='text',extra='')=>`<label>${label}<input id="${id}" type="${type}" value="${esc(value)}" ${extra}></label>`;
function adminSeason(){return adminFrame('シーズンと報酬設定','admin-season',`<div class="surface"><div class="fields">${field('シーズン名','season-title',renewal.seasonTitle)}${field('開始日','season-start',renewal.seasonStart,'date')}${field('終了日','season-end',renewal.seasonEnd,'date')}</div><p class="small">月初開始・同月末終了。最大到達額は最後の報酬地点の金額になります。</p><div class="admin-scroll"><table class="settings-table"><thead><tr><th>到達金額 円</th><th>報酬名</th><th>種別</th><th>数量</th><th>アイコン</th><th></th></tr></thead><tbody>${renewal.milestones.map((m,i)=>`<tr><td><input type="number" data-ms="amount" data-i="${i}" value="${m.amount}"></td><td><input data-ms="name" data-i="${i}" value="${esc(m.name)}"></td><td><select data-ms="kind" data-i="${i}">${['特典Pt','RUSHチケット','クーポン','限定商品'].map(k=>`<option ${k===m.kind?'selected':''}>${k}</option>`).join('')}</select></td><td><input type="number" data-ms="qty" data-i="${i}" value="${m.qty}"></td><td><input type="file" accept="image/png,image/jpeg,image/webp" data-reward-image="${i}"></td><td>${btn('削除','v2-ms-remove:'+i,'subtle')}</td></tr>`).join('')}</tbody></table></div><div class="product-actions">${btn('報酬地点を追加','v2-ms-add','outline')}${btn('設定を保存・プレビュー','v2-season-save')}</div><div id="v2-error" class="validation" role="alert"></div></div>${seasonCard()}`);}
function adminTheme(){const t=themeValues();return adminFrame('季節とイベントの着せ替え','admin-theme',`<div class="surface"><h2>プリセットを選ぶ</h2><div class="theme-options">${Object.entries(SYS.themes).map(([id,v])=>`<button class="theme-option ${renewal.theme===id?'active':''}" style="background:${v.panel};color:${v.accent}" data-action="v2-theme:${id}">${v.tip} ${v.name}</button>`).join('')}</div><div class="fields"><label><input id="global-theme" type="checkbox" ${renewal.globalTheme?'checked':''}> 通常ガチャ画面にもテーマカラーを適用</label>${[['primary','主操作ボタン'],['background','サイト背景'],['track','ゲージ背景色'],['fill','ゲージ進行色'],['panel','パス背景色'],['accent','文字アクセント']].map(([k,n])=>field(n,'theme-'+k,t[k],'color')).join('')}${[['track','ゲージ本体'],['fill','進行部分'],['background','パス背景'],['tip','先端キャラクター'],['decor','周辺装飾'],['rankDecor','ランク周辺装飾']].map(([k,n])=>`<label>${n}の画像<input type="file" data-theme-image="${k}" accept="image/png,image/jpeg,image/webp"><span class="asset-status">${renewal.assets[k]?'画像設定済み':'未設定 / 標準表示'} · 2MB以下</span></label>`).join('')}</div><div class="product-actions">${btn('保存してプレビュー','v2-theme-save')}${btn('画像を全て解除','v2-theme-clear','outline')}</div><p class="small">配置と操作は固定し、色・画像だけを差し替えます。画像は装飾専用で、重要な文字はHTMLで表示します。</p></div>${seasonCard()}${rankCard()}`);}
function adminJP(){return adminFrame('JP対象オリパと専用商品','admin-jp',`<div class="surface"><h2>集計対象期間</h2><div class="fields">${field('開始日','jp-start',renewal.jpStart,'date')}${field('終了日','jp-end',renewal.jpEnd,'date')}</div><h2>オリパごとの加算対象</h2><table class="settings-table"><thead><tr><th>オリパ</th><th>消費PtをJPへ加算</th></tr></thead><tbody>${D.products.map(p=>`<tr><td>${esc(p.name)}</td><td><input type="checkbox" data-eligible="${p.id}" ${renewal.eligible[p.id]?'checked':''}></td></tr>`).join('')}${renewal.jpGames.map(g=>`<tr><td>${esc(g.name)}（JP専用）</td><td><input type="checkbox" data-eligible="${g.id}" ${renewal.eligible[g.id]?'checked':''}></td></tr>`).join('')}</tbody></table><h2 style="margin-top:25px">JPガチャの必要資産</h2><div class="admin-scroll"><table class="settings-table"><thead><tr><th>名称</th><th>JP枚数</th><th>必要Pt</th></tr></thead><tbody>${renewal.jpGames.map((g,i)=>`<tr><td><input data-jpgame="name" data-i="${i}" value="${esc(g.name)}"></td><td><input data-jpgame="tickets" data-i="${i}" type="number" value="${g.tickets}"></td><td><input data-jpgame="points" data-i="${i}" type="number" value="${g.points}"></td></tr>`).join('')}</tbody></table></div><div class="product-actions">${btn('JP商品を追加','v2-jp-add','outline')}${btn('設定を保存','v2-jp-save')}</div><div id="v2-error" class="validation" role="alert"></div></div>`);}
function rushSetting(){return renewal.rushSettings[renewal.rushEditing]||(renewal.rushSettings[renewal.rushEditing]={name:D.rushes.find(r=>r.id===renewal.rushEditing)?.name||'NEW RUSH',price:8000,rate:95,maxStages:8,published:true,start:'2026-09-01',end:'2026-09-30',sources:['通常オリパ','確定系オリパ','キャンペーン','Pt購入'],stages:[{from:1,to:3,rate:95,reward:'通常ラインナップ'},{from:4,to:8,rate:95,reward:'上位ラインナップ'}],media:{}});}
function adminRush(){const c=rushSetting();return adminFrame('RUSHコンテンツ管理','admin-rush',`<div class="surface"><div class="fields"><label>編集するRUSH<select id="rush-edit">${D.rushes.map(r=>`<option value="${r.id}" ${r.id===renewal.rushEditing?'selected':''}>${esc(r.name)}</option>`).join('')}</select></label>${field('RUSH名','rush-name',c.name)}${field('必要チケット種別','rush-ticket',renewal.rushEditing,'text','readonly')}${field('チケット価格 Pt','rush-price',c.price,'number')}${field('表示継続率 %','rush-rate',c.rate,'number','min="0" max="100" step="0.01"')}${field('最大ステージ数','rush-max',c.maxStages,'number')}${field('開始日','rush-start',c.start,'date')}${field('終了日','rush-end',c.end,'date')}<label><input id="rush-published" type="checkbox" ${c.published?'checked':''}> 公開する</label><label>入手経路（表示例）<p class="small">通常オリパ / チケット確定系 / キャンペーン / Pt購入</p></label>${[['thumb','サムネイル'],['ticket','チケット画像'],['start','開始演出'],['continue','継続演出'],['end','終了演出']].map(([k,n])=>`<label>${n}<input type="file" data-rush-media="${k}" accept="image/png,image/jpeg,image/webp"><span class="asset-status">${c.media[k]?'画像設定済み':'未設定 / CSS演出を使用'} · モックは画像のみ</span></label>`).join('')}</div><h2>段階ごとの抽選設定</h2><div class="admin-scroll"><table class="settings-table"><thead><tr><th>開始段階</th><th>終了段階</th><th>継続率 %</th><th>報酬テーブル</th></tr></thead><tbody>${c.stages.map((g,i)=>`<tr>${['from','to','rate','reward'].map(k=>`<td><input data-stage="${k}" data-i="${i}" type="${k==='reward'?'text':'number'}" value="${esc(g[k])}"></td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="small">本番では報酬テーブルIDと商品別重み・在庫を接続します。段階設定は固定デモの当選結果を変更しません。</p><div class="product-actions">${btn('新しいRUSHを追加','v2-rush-add','outline')}${btn('設定を保存','v2-rush-save')}</div><div id="v2-error" class="validation" role="alert"></div></div>`);}
play=function(){return oldPlay().replace('<div class="play-actions">',`<div class="stage-band">${Array.from({length:8},(_,i)=>`<span class="${state.step>i?'done':''}">${i+1}</span>`).join('')}</div><p class="small" style="color:#edc078">${state.step>=4?'上位ステージの演出例':'次のステージへ'}</p><div class="play-actions">`);};
render=function(){const r=route();oldRender();const pages={rank:rankPage,season:seasonPage,'admin-season':adminSeason,'admin-theme':adminTheme,'admin-jp':adminJP,'admin-rush':adminRush};if(pages[r])$('#app').innerHTML=pages[r]();const t=themeValues();document.documentElement.style.setProperty('--red',renewal.globalTheme?t.primary:'#b20d28');document.documentElement.style.setProperty('--bg',renewal.globalTheme?t.background:'#f6f6f8');};
function validMonth(start,end){if(!/^\d{4}-\d{2}-01$/.test(start))return false;const date=new Date(start+'T00:00:00Z');date.setUTCMonth(date.getUTCMonth()+1);date.setUTCDate(0);return end===date.toISOString().slice(0,10);}
const showError=text=>{const e=$('#v2-error');if(e)e.textContent=text;else toast(text);};
act=function(a){
 const [key,value]=a.split(':');
 if(!key.startsWith('v2-')){
   if(key==='admin-save'){const err=validateConfig();if(err)return showError(err);localStorage.setItem('grim-jp-config-v2',JSON.stringify({rankConfigs:state.adminConfigs}));toast('新ランクのJP条件を保存しました');return;}
   if(key==='charge')return act('v2-charge');
   const before=state.coins;oldAct(a);
   if(key==='draw')renewal.pendingSource=value;
   if(key==='confirm'&&state.coins<before&&renewal.pendingSource){if(renewal.eligible[renewal.pendingSource])renewal.monthlySpend+=before-state.coins;renewal.pendingSource=null;}
   if(['close','buy','start','demo','jp-draw'].includes(key))renewal.pendingSource=null;
   return;
 }
 if(key==='v2-rank-apply'){const amount=Number($('#lifetime-demo').value);if(!Number.isSafeInteger(amount)||amount<0)return toast('0以上の整数を入力してください');renewal.lifetime=amount;render();}
 else if(key==='v2-legend'){renewal.lifetime=65000000;render();}
 else if(key==='v2-rank-up'){const r=rankFor(renewal.lifetime);modal(`<div class="rank-up"><span class="eyebrow">RANK UP</span><h2>${r.name}</h2><div style="width:100px;margin:20px auto;color:${r.color}">${crownSvg}</div><p>Lv.${r.level} に到達しました</p><p class="small">演出サンプル</p></div>${btn('次へ','close','full')}`);}
 else if(key==='v2-charge'){renewal.lifetime+=12500;renewal.monthlyCharge+=12500;state.coins+=12500;toast('課金デモ：累計・当月課金に12,500円加算（Pt付与は仮の1円＝1Pt）');render();}
 else if(key==='v2-season-full'){renewal.monthlyCharge=renewal.milestones.at(-1).amount;render();}
 else if(key==='v2-season-reset'){renewal.monthlyCharge=0;renewal.claimed=[];toast('進捗0の表示例。累計ランクは維持します');render();}
 else if(key==='v2-claim'){const i=Number(value),m=renewal.milestones[i];if(!m||renewal.claimed.includes(i)||renewal.monthlyCharge<m.amount)return;renewal.claimed.push(i);renewal.rewardHistory.push(`${renewal.seasonStart.slice(0,7)} ${m.name} / ${m.kind} × ${m.qty}`);toast('報酬の受取を記録しました（モック）');render();}
 else if(key==='v2-theme'){renewal.theme=value;renewal.themeOverrides={};renewal.seasonTitle=SYS.themes[value].title;render();}
 else if(key==='v2-theme-save'){for(const k of ['primary','background','track','fill','panel','accent'])renewal.themeOverrides[k]=$('#theme-'+k).value;renewal.globalTheme=$('#global-theme').checked;saveRenewal();render();}
 else if(key==='v2-theme-clear'){renewal.assets={};render();}
 else if(key==='v2-ms-add'){renewal.milestones.push({amount:renewal.milestones.at(-1).amount+50000,name:'追加報酬',kind:'特典Pt',qty:100,icon:'✦'});render();}
 else if(key==='v2-ms-remove'){if(renewal.milestones.length<=1)return toast('1地点以上が必要です');renewal.milestones.splice(Number(value),1);render();}
 else if(key==='v2-season-save'){let prev=0;for(const m of renewal.milestones){if(!Number.isSafeInteger(m.amount)||m.amount<=prev||!m.name||!Number.isSafeInteger(m.qty)||m.qty<=0)return showError('金額は正整数の昇順、名称は必須、数量は正整数です');prev=m.amount;}const start=$('#season-start').value,end=$('#season-end').value;if(!validMonth(start,end))return showError('開始日を月初、終了日を同月末にしてください');renewal.seasonStart=start;renewal.seasonEnd=end;renewal.seasonTitle=$('#season-title').value;saveRenewal();render();}
 else if(key==='v2-jp-add'){renewal.jpGames.push({id:'jp'+Date.now(),name:'NEW JP',tickets:1,points:1000});render();}
 else if(key==='v2-jp-save'){if(renewal.jpGames.some(g=>!g.name||!Number.isSafeInteger(g.tickets)||g.tickets<1||!Number.isSafeInteger(g.points)||g.points<1))return showError('商品名と正整数の枚数・Ptが必要です');if(!validMonth($('#jp-start').value,$('#jp-end').value))return showError('集計は月初〜同月末を指定してください');renewal.jpStart=$('#jp-start').value;renewal.jpEnd=$('#jp-end').value;saveRenewal();}
 else if(key==='v2-jp-draw'){const g=renewal.jpGames[Number(value)],fail=['locked','expired','scheduled'].includes(state.jpMode)||state.jp<g.tickets||state.coins<g.points;modal(`<h2>${esc(g.name)}</h2><div class="dual-price">JP ${g.tickets}枚 ＋ ${fmt(g.points)} Pt</div><p>保有：JP ${state.jp}枚 / ${fmt(state.coins)} Pt</p>${fail?'<div class="error-box">期間外、またはJPチケット・Ptが不足しています。</div>':''}<p class="small">サンプル抽選。実際の取引は発生しません。</p><div class="actions">${btn('戻る','close','outline')}${btn('両方を使って引く','confirm','',fail?'disabled':'')}</div>`,()=>{if(fail)return;state.jp-=g.tickets;state.coins-=g.points;if(renewal.eligible[g.id])renewal.monthlySpend+=g.points;state.earned.push(0);go('history');});}
 else if(key==='v2-rush-add'){const id='custom'+Date.now();D.rushes.push({id,name:'NEW RUSH',rate:95,price:8000,theme:'crimson',subtitle:'新しいRUSH'});state.tickets[id]=0;renewal.rushEditing=id;render();}
 else if(key==='v2-rush-save'){const c=rushSetting();c.name=$('#rush-name').value;c.price=Number($('#rush-price').value);c.rate=Number($('#rush-rate').value);c.maxStages=Number($('#rush-max').value);c.start=$('#rush-start').value;c.end=$('#rush-end').value;c.published=$('#rush-published').checked;if(!c.name||!Number.isSafeInteger(c.price)||c.price<1||c.rate<0||c.rate>100||!Number.isSafeInteger(c.maxStages)||c.maxStages<1||c.end<c.start)return showError('名称、価格、継続率、最大段階、期間を確認してください');let next=1;for(const s of c.stages){if(s.from!==next||s.to<s.from||s.rate<0||s.rate>100||!s.reward)return showError('段階は1から連続し、報酬テーブルを設定してください');next=s.to+1;}if(next-1!==c.maxStages)return showError('最終段階と最大ステージ数を一致させてください');Object.assign(D.rushes.find(r=>r.id===renewal.rushEditing),{name:c.name,price:c.price,rate:c.rate});saveRenewal();}
};
document.addEventListener('input',e=>{const d=e.target.dataset,i=Number(d.i);if(d.ms)renewal.milestones[i][d.ms]=['amount','qty'].includes(d.ms)?Number(e.target.value):e.target.value;if(d.jpgame)renewal.jpGames[i][d.jpgame]=d.jpgame==='name'?e.target.value:Number(e.target.value);if(d.stage)rushSetting().stages[i][d.stage]=d.stage==='reward'?e.target.value:Number(e.target.value);});
document.addEventListener('change',e=>{const d=e.target.dataset;if(e.target.id==='rush-edit'){renewal.rushEditing=e.target.value;render();}if(d.eligible)renewal.eligible[d.eligible]=e.target.checked;if(d.themeImage||d.rewardImage!==undefined||d.rushMedia){const file=e.target.files[0];if(!file)return;if(file.size>2*1024*1024||!['image/png','image/jpeg','image/webp'].includes(file.type))return toast('PNG/JPEG/WebP、2MB以下を選んでください');const reader=new FileReader();reader.onload=()=>{if(d.themeImage)renewal.assets[d.themeImage]=reader.result;else if(d.rushMedia)rushSetting().media[d.rushMedia]=reader.result;else renewal.milestones[Number(d.rewardImage)].image=reader.result;toast('画像を読み込みました。保存・プレビューで反映できます');};reader.readAsDataURL(file);}});
screens.push(['L01','rank','累計ランクとLv.','11ランク・Lv.999・LEGENDの★'],['S01','season','GRIM SEASON PASS','当月課金・次の報酬・受取'],['A02','admin-season','シーズン報酬設定','到達金額・報酬数・画像'],['A03','admin-theme','テーマ着せ替え','8テーマ・画像・色・全体適用'],['A04','admin-jp','JP対象と商品','商品別の加算可否・必要資産'],['A05','admin-rush','RUSH管理','種類追加・段階・演出素材']);
render();
// 管理で登録したRUSHは再読込後も同じIDで表示する。
for(const [id,c] of Object.entries(renewal.rushSettings)){
  let r=D.rushes.find(r=>r.id===id);
  if(!r){r={id,name:c.name,rate:c.rate,price:c.price,theme:'crimson',subtitle:'GRIM ORIGINAL'};D.rushes.push(r);state.tickets[id]=0;}
  Object.assign(r,{name:c.name,rate:c.rate,price:c.price});
}
const oldCover=cover,oldRushList=rushList;
cover=function(r,detail=false){const image=renewal.rushSettings[r.id]?.media?.thumb;return image?`<img class="product-cover" src="${image}" alt="${esc(r.name)}">`:oldCover(r,detail);};
rushList=function(){const all=D.rushes;D.rushes=all.filter(r=>renewal.rushSettings[r.id]?.published!==false);const html=oldRushList();D.rushes=all;return html;};
const v2Admin=admin,v2Act=act;
admin=function(){return v2Admin().replace('10ゲージ × 5スロット（初期構成）','10ゲージ・初期5スロット（地点は追加・削除可能）').replace('<div id="admin-validation"',`<div class="product-actions">${btn('到達地点を追加','v2-slot-add','outline')}${btn('最後の地点を削除','v2-slot-remove','subtle')}</div><div id="admin-validation"`);};
act=function(a){
 if(a==='v2-slot-add'){const g=config()[state.adminGauge],end=g.at(-1).threshold,next=config()[state.adminGauge+1]?.[0]?.threshold;if(next&&next-end<2)return toast('次ゲージとの閾値間隔を空けてください');g.push({threshold:next?Math.floor((end+next)/2):end+10000,reward:5});state.saved=false;render();return;}
 if(a==='v2-slot-remove'){const g=config()[state.adminGauge];if(g.length<=1)return toast('1地点以上が必要です');g.pop();state.saved=false;render();return;}
 if(a==='admin-save'&&(!$('#effective-month').value||$('#effective-month').value<'2026-10'))return showError('適用開始月は2026年10月以降を指定してください');
 v2Act(a);
};
render();

